//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.RssFeedReaderService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RssFeedItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RssFeedItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebApplication1.RssFeedReaderService.RssFeedReaderServiceSoap")]
    public interface RssFeedReaderServiceSoap
    {
        
        // CODEGEN: Контракт генерации сообщений с именем urlText из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFeed", ReplyAction="*")]
        WebApplication1.RssFeedReaderService.GetFeedResponse GetFeed(WebApplication1.RssFeedReaderService.GetFeedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFeed", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.RssFeedReaderService.GetFeedResponse> GetFeedAsync(WebApplication1.RssFeedReaderService.GetFeedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFeedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFeed", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.RssFeedReaderService.GetFeedRequestBody Body;
        
        public GetFeedRequest()
        {
        }
        
        public GetFeedRequest(WebApplication1.RssFeedReaderService.GetFeedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFeedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string urlText;
        
        public GetFeedRequestBody()
        {
        }
        
        public GetFeedRequestBody(string urlText)
        {
            this.urlText = urlText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFeedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFeedResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.RssFeedReaderService.GetFeedResponseBody Body;
        
        public GetFeedResponse()
        {
        }
        
        public GetFeedResponse(WebApplication1.RssFeedReaderService.GetFeedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFeedResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.RssFeedReaderService.RssFeedItem[] GetFeedResult;
        
        public GetFeedResponseBody()
        {
        }
        
        public GetFeedResponseBody(WebApplication1.RssFeedReaderService.RssFeedItem[] GetFeedResult)
        {
            this.GetFeedResult = GetFeedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RssFeedReaderServiceSoapChannel : WebApplication1.RssFeedReaderService.RssFeedReaderServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RssFeedReaderServiceSoapClient : System.ServiceModel.ClientBase<WebApplication1.RssFeedReaderService.RssFeedReaderServiceSoap>, WebApplication1.RssFeedReaderService.RssFeedReaderServiceSoap
    {
        
        public RssFeedReaderServiceSoapClient()
        {
        }
        
        public RssFeedReaderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public RssFeedReaderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RssFeedReaderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RssFeedReaderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.RssFeedReaderService.GetFeedResponse WebApplication1.RssFeedReaderService.RssFeedReaderServiceSoap.GetFeed(WebApplication1.RssFeedReaderService.GetFeedRequest request)
        {
            return base.Channel.GetFeed(request);
        }
        
        public WebApplication1.RssFeedReaderService.RssFeedItem[] GetFeed(string urlText)
        {
            WebApplication1.RssFeedReaderService.GetFeedRequest inValue = new WebApplication1.RssFeedReaderService.GetFeedRequest();
            inValue.Body = new WebApplication1.RssFeedReaderService.GetFeedRequestBody();
            inValue.Body.urlText = urlText;
            WebApplication1.RssFeedReaderService.GetFeedResponse retVal = ((WebApplication1.RssFeedReaderService.RssFeedReaderServiceSoap)(this)).GetFeed(inValue);
            return retVal.Body.GetFeedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.RssFeedReaderService.GetFeedResponse> WebApplication1.RssFeedReaderService.RssFeedReaderServiceSoap.GetFeedAsync(WebApplication1.RssFeedReaderService.GetFeedRequest request)
        {
            return base.Channel.GetFeedAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.RssFeedReaderService.GetFeedResponse> GetFeedAsync(string urlText)
        {
            WebApplication1.RssFeedReaderService.GetFeedRequest inValue = new WebApplication1.RssFeedReaderService.GetFeedRequest();
            inValue.Body = new WebApplication1.RssFeedReaderService.GetFeedRequestBody();
            inValue.Body.urlText = urlText;
            return ((WebApplication1.RssFeedReaderService.RssFeedReaderServiceSoap)(this)).GetFeedAsync(inValue);
        }
    }
}
